---
annotations:
  screwdriver.cd/chainPR: false

jobs:
  graphgpt-unit-tests:
    requires: [~pr, ~commit]
    image: buildpack-deps:22.04-scm
    steps:
      - install-python: sd-cmd exec QubitPi/install-python-310@latest
      - install-dependencies: pip3 install -r mlflow_models/HanLPner/requirements.txt
      - run-tests: python3 -m unittest mlflow_models/HanLPner/test_parser.py

  speech-recognition-flask-unit-tests:
    requires: [~pr, ~commit]
    image: buildpack-deps:22.04-scm
    steps:
      - install-python: sd-cmd exec QubitPi/install-python-310@latest
      - install-dependencies: pip3 install -r flask_ws/speechrecognition/requirements.txt
      - run-tests: python3 -m unittest flask_ws/speechrecognition/test__init__.py
